/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/sections/About.vue')['default']
    Clients: typeof import('./src/components/sections/Clients.vue')['default']
    Contact: typeof import('./src/components/sections/Contact.vue')['default']
    Home: typeof import('./src/components/sections/Home.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Portfolio: typeof import('./src/components/sections/Portfolio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./src/components/sections/Services.vue')['default']
    SinglePageLayout: typeof import('./src/components/SinglePageLayout.vue')['default']
  }
}
